# Generated by Django 5.2.17 on 2026-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_source_isolation_and_worker_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='next_dispatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
