# Generated by Django 5.2.17 on 2026-08-14 06:33

import django.db.models.deletion
from django.db import migrations, models


def populate_song_targets(apps, schema_editor):
    AnalysisTask = apps.get_model("analysis", "AnalysisTask")
    AnalysisTask.objects.filter(song_id__isnull=False, target_id__isnull=True).update(target_type="song", target_id=models.F("song_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysistask_next_dispatch_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysistask',
            name='analysis_task_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='analysistask',
            name='analysis_executor_valid',
        ),
        migrations.AddField(
            model_name='analysistask',
            name='target_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='target_type',
            field=models.CharField(choices=[('song', '歌曲'), ('singing_session', '演唱会话')], default='song', max_length=24),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_tasks', to='songs.song'),
        ),
        migrations.RunPython(populate_song_targets, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analysistask',
            name='task_type',
            field=models.CharField(choices=[('vocal_separation', '人声分离'), ('accompaniment_generation', '伴奏生成'), ('lyrics_recognition', '歌词识别'), ('singing_audio_metrics', '演唱音频指标'), ('face_landmarks', '面部关键点')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.CheckConstraint(condition=models.Q(('task_type__in', ['vocal_separation', 'accompaniment_generation', 'lyrics_recognition', 'singing_audio_metrics', 'face_landmarks'])), name='analysis_task_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.CheckConstraint(condition=models.Q(('executor__in', ['mock_song', 'mock_singing'])), name='analysis_executor_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('executor', 'mock_song'), ('song__isnull', False), ('target_id', models.F('song_id')), ('target_type', 'song'), ('task_type__in', ['vocal_separation', 'accompaniment_generation', 'lyrics_recognition'])), models.Q(('executor', 'mock_singing'), ('song__isnull', True), ('target_id__isnull', False), ('target_type', 'singing_session'), ('task_type__in', ['singing_audio_metrics', 'face_landmarks'])), _connector='OR'), name='analysis_task_target_contract_valid'),
        ),
    ]
