# Generated by Django 5.2.17 on 2026-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_analysistask_analysis_task_type_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 0)), name='analysis_task_generation_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['target_type', 'target_id', 'generation', 'task_type'], name='analysis_task_target_gen_idx'),
        ),
    ]
