# Generated by Django 5.2.17 on 2026-08-14 07:56

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def guard_latest_generation_downgrade(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing = set(connection.introspection.table_names(cursor))
    tables = ["analysis_analysistask"]
    if "singing_singingsession" in existing:
        tables.extend((
            "singing_analysistimeseries",
            "singing_sessionmedia",
            "singing_singingsession",
        ))
    if connection.vendor == "postgresql":
        quoted = ", ".join(connection.ops.quote_name(table) for table in sorted(tables))
        with connection.cursor() as cursor:
            cursor.execute(f"LOCK TABLE {quoted} IN ACCESS EXCLUSIVE MODE")
    elif connection.vendor != "sqlite":
        raise IrreversibleError("当前数据库不支持安全回退分析代际闭合")
    AnalysisTask = apps.get_model("analysis", "AnalysisTask")
    has_session = False
    if "singing_singingsession" in existing:
        with connection.cursor() as cursor:
            cursor.execute('SELECT EXISTS(SELECT 1 FROM "singing_singingsession")')
            has_session = cursor.fetchone()[0]
    if (
        has_session
        or AnalysisTask.objects.using(connection.alias).filter(
            target_type="singing_session"
        ).exists()
    ):
        raise IrreversibleError("演唱分析代际数据无法无损降级")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysisresult_generation_analysistask_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='generation',
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type', 'singing_session')), fields=('target_type', 'target_id', 'generation', 'task_type'), name='analysis_singing_task_generation_unique'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_latest_generation_downgrade),
    ]
