# Generated by Django 5.2.17 on 2026-08-13 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def assign_token_families(apps, schema_editor):
    refresh_token = apps.get_model("accounts", "RefreshToken")
    for token in refresh_token.objects.filter(family_id__isnull=True).iterator():
        token.family_id = uuid.uuid4()
        token.save(update_fields=["family_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.RunPython(assign_token_families, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor', to='accounts.refreshtoken'),
        ),
    ]
