# Generated by Django 5.2.17 on 2026-08-14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("patients", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("owner_type", models.CharField(choices=[("patient", "患者")], default="patient", max_length=16)),
                ("media_type", models.CharField(max_length=32)),
                ("backend", models.CharField(max_length=16)),
                ("object_key", models.CharField(max_length=255, unique=True)),
                ("mime", models.CharField(max_length=127)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("uploading", "上传中"), ("ready", "可用"), ("failed", "失败"), ("pending_cleanup", "待清理")], default="uploading", max_length=24)),
                ("upload_expires_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="media_assets", to="patients.patientprofile")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="mediaasset", index=models.Index(fields=["owner", "status"], name="media_media_owner_i_f272bb_idx")),
        migrations.AddIndex(model_name="mediaasset", index=models.Index(fields=["media_type", "status"], name="media_media_media_t_936e77_idx")),
    ]
