# Generated by Django 5.2.17 on 2026-08-13 19:39

import re

from django.db import migrations, models


_HEX64 = re.compile(r"^[0-9a-f]{64}$")


def mark_legacy_local_ready_for_runtime_conversion(apps, schema_editor):
    """只迁移数据库；媒体文件可能未挂载，schema migration 绝不能触碰存储。"""
    MediaAsset = apps.get_model("media", "MediaAsset")
    for asset in MediaAsset.objects.filter(backend="local", status="ready"):
        metadata = dict(asset.metadata or {})
        if _HEX64.fullmatch(asset.sha256 or ""):
            asset.manifest_generation = asset.id.hex
            metadata["local_layout"] = "legacy_pending_v0_or_v1"
            metadata["migration_pending"] = True
            asset.metadata = metadata
            asset.save(update_fields=["manifest_generation", "metadata"])
        else:
            # 文件系统不可用于迁移判断；仅 DB 自身已经缺少可信 hash 时才无法满足新约束。
            metadata["local_migration_reason"] = "legacy_database_receipt_invalid"
            asset.status = "failed"
            asset.manifest_generation = ""
            asset.metadata = metadata
            asset.save(update_fields=["status", "manifest_generation", "metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0007_media_type_constraint"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="mediaasset", name="media_asset_ready_receipt_valid"),
        migrations.RemoveConstraint(model_name="mediaasset", name="media_asset_status_valid"),
        migrations.AddField(
            model_name="mediaasset",
            name="manifest_generation",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="status",
            field=models.CharField(choices=[("uploading", "上传中"), ("receiving", "接收中"), ("staged", "已暂存"), ("ready", "可用"), ("failed", "失败"), ("pending_cleanup", "待清理")], default="uploading", max_length=24),
        ),
        migrations.RunPython(mark_legacy_local_ready_for_runtime_conversion, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("media_type__in", ["singing_audio", "singing_video"]), ("owner_type", "patient")), models.Q(("media_type__in", ["lyrics", "song_accompaniment", "song_source", "song_vocal"]), ("owner_type", "song")), models.Q(("media_type__in", ["lyrics", "song_accompaniment", "song_vocal", "waveform"]), ("owner_type", "system")), models.Q(("media_type__in", ["export"]), ("owner_type", "export")), _connector="OR"), name="media_asset_owner_media_valid"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ["uploading", "receiving", "staged", "ready", "failed", "pending_cleanup"])), name="media_asset_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("backend", "local"), ("status", "receiving"), ("upload_lease_expires_at__isnull", False), ("upload_nonce__isnull", False)), models.Q(models.Q(("status", "receiving"), _negated=True), ("upload_lease_expires_at__isnull", True), ("upload_nonce__isnull", True)), _connector="OR"), name="media_asset_upload_lease_valid"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("backend", "local"), ("manifest_generation__regex", "^[0-9a-f]{32}$"), ("sha256__regex", "^[0-9a-f]{64}$"), ("status__in", ["staged", "ready"])), models.Q(("backend", "qiniu"), ("etag__gt", ""), ("manifest_generation", ""), ("status", "ready")), models.Q(("status__in", ["staged", "ready"]), _negated=True), _connector="OR"), name="media_asset_ready_receipt_valid"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("backend", "local"), ("status", "staged")), models.Q(("status", "staged"), _negated=True), _connector="OR"), name="media_asset_staged_local_only"),
        ),
    ]
