# Generated by Django 5.2.17 on 2026-08-13 19:39

import hashlib
import json
import os
from pathlib import Path
from tempfile import NamedTemporaryFile

from django.conf import settings
from django.db import migrations, models


def backfill_legacy_local_ready(apps, schema_editor):
    MediaAsset = apps.get_model("media", "MediaAsset")
    root = Path(settings.MEDIA_LOCAL_ROOT).resolve()
    for asset in MediaAsset.objects.filter(backend="local", status="ready"):
        metadata = dict(asset.metadata or {})
        try:
            parts = asset.object_key.split("/")
            if not asset.object_key or asset.object_key.startswith("/") or "\\" in asset.object_key or "%" in asset.object_key or any(part in {"", ".", ".."} for part in parts):
                raise ValueError("unsafe key")
            data_path = (root / asset.object_key).resolve()
            if root not in data_path.parents:
                raise ValueError("escaped key")
            sidecar_path = data_path.with_name(f".{data_path.name}.metadata.json")
            with sidecar_path.open(encoding="utf-8") as source:
                sidecar = json.load(source)
            if set(sidecar) != {"mime", "size", "sha256"} or sidecar != {"mime": asset.mime, "size": asset.size, "sha256": asset.sha256} or not data_path.is_file() or data_path.stat().st_size != asset.size:
                raise ValueError("metadata mismatch")
            digest = hashlib.sha256()
            with data_path.open("rb") as source:
                while chunk := source.read(64 * 1024):
                    digest.update(chunk)
            if digest.hexdigest() != asset.sha256:
                raise ValueError("hash mismatch")
            asset.manifest_generation = asset.id.hex
            metadata["local_layout"] = "legacy_sidecar_v1"
            asset.metadata = metadata
            asset.save(update_fields=["manifest_generation", "metadata"])
        except (OSError, ValueError, TypeError, json.JSONDecodeError):
            metadata["local_migration_previous_status"] = "ready"
            metadata["local_migration_reason"] = "legacy_file_evidence_missing_or_invalid"
            asset.status = "failed"
            asset.manifest_generation = ""
            asset.metadata = metadata
            asset.save(update_fields=["status", "manifest_generation", "metadata"])


def reverse_legacy_local_ready(apps, schema_editor):
    MediaAsset = apps.get_model("media", "MediaAsset")
    for asset in MediaAsset.objects.filter(backend="local"):
        metadata = dict(asset.metadata or {})
        if metadata.get("local_layout") == "legacy_sidecar_v1":
            root = Path(settings.MEDIA_LOCAL_ROOT).resolve()
            data_path = (root / asset.object_key).resolve()
            manifest_path = root / ".manifests" / f"{asset.object_key}.json"
            if not data_path.exists() and manifest_path.is_file() and root in data_path.parents:
                try:
                    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                    blob_path = (root / ".blobs" / manifest["blob"]).resolve()
                    if (
                        manifest.get("object_key") != asset.object_key or manifest.get("asset_id") != str(asset.id)
                        or manifest.get("generation") != asset.manifest_generation or manifest.get("sha256") != asset.sha256
                        or manifest.get("size") != asset.size or manifest.get("mime") != asset.mime
                        or blob_path.parent != (root / ".blobs").resolve() or not blob_path.is_file()
                    ):
                        raise ValueError("manifest mismatch")
                    data_path.parent.mkdir(parents=True, exist_ok=True)
                    temporary = NamedTemporaryFile(dir=data_path.parent, prefix=".legacy-rollback-", delete=False)
                    digest = hashlib.sha256(); size = 0
                    with temporary, blob_path.open("rb") as source:
                        while chunk := source.read(64 * 1024):
                            size += len(chunk); digest.update(chunk); temporary.write(chunk)
                        temporary.flush(); os.fsync(temporary.fileno())
                    if size != asset.size or digest.hexdigest() != asset.sha256:
                        raise ValueError("blob mismatch")
                    os.replace(temporary.name, data_path)
                    sidecar_path = data_path.with_name(f".{data_path.name}.metadata.json")
                    sidecar_path.write_text(json.dumps({"mime": asset.mime, "size": asset.size, "sha256": asset.sha256}), encoding="utf-8")
                except (OSError, ValueError, TypeError, KeyError, json.JSONDecodeError):
                    # 无法无损恢复旧布局时拒绝伪造 READY；回退后的旧应用会看到 failed。
                    asset.status = "failed"
        if metadata.pop("local_migration_previous_status", None) == "ready":
            asset.status = "ready"
        metadata.pop("local_migration_reason", None)
        metadata.pop("local_layout", None)
        asset.metadata = metadata
        asset.save(update_fields=["status", "metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_media_type_constraint'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='media_asset_ready_receipt_valid',
        ),
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='media_asset_status_valid',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='manifest_generation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('receiving', '接收中'), ('staged', '已暂存'), ('ready', '可用'), ('failed', '失败'), ('pending_cleanup', '待清理')], default='uploading', max_length=24),
        ),
        migrations.RunPython(backfill_legacy_local_ready, reverse_legacy_local_ready),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type__in', ['singing_audio', 'singing_video']), ('owner_type', 'patient')), models.Q(('media_type__in', ['lyrics', 'song_accompaniment', 'song_source', 'song_vocal']), ('owner_type', 'song')), models.Q(('media_type__in', ['lyrics', 'song_accompaniment', 'song_vocal', 'waveform']), ('owner_type', 'system')), models.Q(('media_type__in', ['export']), ('owner_type', 'export')), _connector='OR'), name='media_asset_owner_media_valid'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['uploading', 'receiving', 'staged', 'ready', 'failed', 'pending_cleanup'])), name='media_asset_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('backend', 'local'), ('status', 'receiving'), ('upload_lease_expires_at__isnull', False), ('upload_nonce__isnull', False)), models.Q(models.Q(('status', 'receiving'), _negated=True), ('upload_lease_expires_at__isnull', True), ('upload_nonce__isnull', True)), _connector='OR'), name='media_asset_upload_lease_valid'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('backend', 'local'), ('manifest_generation__regex', '^[0-9a-f]{32}$'), ('sha256__regex', '^[0-9a-f]{64}$'), ('status__in', ['staged', 'ready'])), models.Q(('backend', 'qiniu'), ('etag__gt', ''), ('manifest_generation', ''), ('status', 'ready')), models.Q(('status__in', ['staged', 'ready']), _negated=True), _connector='OR'), name='media_asset_ready_receipt_valid'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('backend', 'local'), ('status', 'staged')), models.Q(('status', 'staged'), _negated=True), _connector='OR'), name='media_asset_staged_local_only'),
        ),
    ]
