# Generated by Django 5.2.17 on 2026-08-13 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medical_record_no', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('enrollment_age', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='doctors.doctorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['medical_record_no'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('cycle_weeks', models.PositiveSmallIntegerField()),
                ('target_session_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'active')), fields=('patient',), name='one_active_treatment_plan_per_patient')],
            },
        ),
    ]
