# Generated by Django 5.2.17 on 2026-08-14 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def guard_singing_table_drop(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        tables = (
            "analysis_analysistask",
            "singing_analysistimeseries",
            "singing_sessionmedia",
            "singing_singingsession",
        )
        quoted = ", ".join(connection.ops.quote_name(table) for table in tables)
        with connection.cursor() as cursor:
            cursor.execute(
                f"LOCK TABLE {quoted} IN ACCESS EXCLUSIVE MODE "
                "/* singing_table_destructive_barrier */"
            )
    elif connection.vendor != "sqlite":
        raise IrreversibleError("当前数据库不支持安全删除演唱表")
    SingingSession = apps.get_model("singing", "SingingSession")
    AnalysisTask = apps.get_model("analysis", "AnalysisTask")
    if (
        SingingSession.objects.using(connection.alias).exists()
        or AnalysisTask.objects.using(connection.alias).filter(
            target_type="singing_session"
        ).exists()
    ):
        raise IrreversibleError("演唱数据无法无损删除")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0004_remove_analysistask_analysis_task_type_valid_and_more'),
        ('media', '0001_initial'),
        ('patients', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_snapshot', models.JSONField()),
                ('song_snapshot', models.JSONField()),
                ('treatment_plan_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('created', '已创建'), ('awaiting_upload', '等待上传'), ('uploaded', '已上传'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='created', max_length=24)),
                ('submission_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('retry_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('retry_generation', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('burp_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_source', models.CharField(default='patient_android_api', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='singing_sessions', to='patients.patientprofile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='singing_sessions', to='songs.song')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='singing_sessions', to='patients.treatmentplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('singing_audio', '演唱音频'), ('singing_video', '演唱录像')], max_length=32)),
                ('grant_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='singing_session_binding', to='media.mediaasset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_bindings', to='singing.singingsession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTimeSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=32)),
                ('sample_interval_ms', models.PositiveIntegerField()),
                ('values', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='analysis.analysistask')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='singing.singingsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='singingsession',
            index=models.Index(fields=['patient', 'status', '-created_at'], name='singing_sin_patient_d1c54c_idx'),
        ),
        migrations.AddIndex(
            model_name='singingsession',
            index=models.Index(fields=['status', '-created_at'], name='singing_sin_status_9e0ddf_idx'),
        ),
        migrations.AddConstraint(
            model_name='singingsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'awaiting_upload', 'uploaded', 'processing', 'completed', 'failed', 'cancelled'])), name='singing_session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='singingsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gt', 0), _connector='OR'), name='singing_session_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='singingsession',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='singing_session_score_range'),
        ),
        migrations.AddConstraint(
            model_name='singingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('burp_count__isnull', False), ('completed_at__isnull', False), ('is_mock', True), ('score__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='singing_session_completed_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='sessionmedia',
            constraint=models.UniqueConstraint(fields=('session', 'media_type'), name='one_media_type_per_singing_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('grant_idempotency_key', ''), _negated=True), fields=('session', 'grant_idempotency_key'), name='singing_upload_grant_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='sessionmedia',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['singing_audio', 'singing_video'])), name='singing_session_media_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysistimeseries',
            constraint=models.UniqueConstraint(fields=('task', 'metric_type'), name='one_metric_series_per_analysis_task'),
        ),
        migrations.AddConstraint(
            model_name='analysistimeseries',
            constraint=models.CheckConstraint(condition=models.Q(('sample_interval_ms__gt', 0)), name='analysis_time_series_interval_positive'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_singing_table_drop),
    ]
