# Generated by Django 5.2.17 on 2026-08-14 07:21

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def guard_generation_downgrade(apps, schema_editor):
    SingingSession = apps.get_model("singing", "SingingSession")
    AnalysisTask = apps.get_model("analysis", "AnalysisTask")
    if (
        SingingSession.objects.using(schema_editor.connection.alias).exists()
        or AnalysisTask.objects.using(schema_editor.connection.alias).filter(
            target_type="singing_session",
        ).exists()
    ):
        raise IrreversibleError("演唱会话与代际分析任务无法无损降级")


class Migration(migrations.Migration):

    dependencies = [
        ('singing', '0002_reverse_data_barrier'),
        ('analysis', '0005_analysisresult_generation_analysistask_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistimeseries',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='analysis_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_generation_downgrade),
    ]
