# Generated by Django 5.2.17 on 2026-08-14 07:21

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


LOCKED_TABLES = (
    "analysis_analysistask",
    "singing_analysistimeseries",
    "singing_sessionmedia",
    "singing_singingsession",
)


def lock_singing_write_surface(schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "sqlite":
        return
    if connection.vendor != "postgresql":
        raise IrreversibleError("当前数据库不支持安全回退演唱分析代际")
    quoted = ", ".join(connection.ops.quote_name(table) for table in LOCKED_TABLES)
    with connection.cursor() as cursor:
        cursor.execute(f"LOCK TABLE {quoted} IN ACCESS EXCLUSIVE MODE")


def guard_generation_downgrade(apps, schema_editor):
    lock_singing_write_surface(schema_editor)
    SingingSession = apps.get_model("singing", "SingingSession")
    AnalysisTask = apps.get_model("analysis", "AnalysisTask")
    if (
        SingingSession.objects.using(schema_editor.connection.alias).exists()
        or AnalysisTask.objects.using(schema_editor.connection.alias).filter(
            target_type="singing_session",
        ).exists()
    ):
        raise IrreversibleError("演唱会话与代际分析任务无法无损降级")


class Migration(migrations.Migration):

    dependencies = [
        ('singing', '0002_reverse_data_barrier'),
        ('analysis', '0005_analysisresult_generation_analysistask_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistimeseries',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='analysis_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_generation_downgrade),
    ]
