# Generated by Django 5.2.17 on 2026-08-14 07:56

from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError


def guard_latest_singing_downgrade(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        tables = (
            "analysis_analysistask",
            "singing_analysistimeseries",
            "singing_sessionmedia",
            "singing_singingsession",
        )
        quoted = ", ".join(connection.ops.quote_name(table) for table in tables)
        with connection.cursor() as cursor:
            cursor.execute(f"LOCK TABLE {quoted} IN ACCESS EXCLUSIVE MODE")
    elif connection.vendor != "sqlite":
        raise IrreversibleError("当前数据库不支持安全回退演唱代际闭合")
    SingingSession = apps.get_model("singing", "SingingSession")
    AnalysisTask = apps.get_model("analysis", "AnalysisTask")
    if (
        SingingSession.objects.using(connection.alias).exists()
        or AnalysisTask.objects.using(connection.alias).filter(
            target_type="singing_session"
        ).exists()
    ):
        raise IrreversibleError("演唱代际数据无法无损降级")


class Migration(migrations.Migration):

    dependencies = [
        ('singing', '0003_analysistimeseries_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistimeseries',
            name='generation',
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_latest_singing_downgrade),
    ]
