# Generated by Django 5.2.17 on 2026-08-26 16:24

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def guard_creation_idempotency_downgrade(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute('LOCK TABLE "singing_singingsession" IN ACCESS EXCLUSIVE MODE')
    elif connection.vendor != "sqlite":
        raise IrreversibleError("当前数据库不支持安全回退演唱会话创建幂等")
    SingingSession = apps.get_model("singing", "SingingSession")
    if SingingSession.objects.using(connection.alias).exists():
        raise IrreversibleError("演唱会话创建幂等数据无法无损降级")


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('singing', '0004_remove_analysistimeseries_generation'),
        ('songs', '0004_songavailabilityscanstate_batch_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingsession',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='singingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_idempotency_key', ''), _negated=True), fields=('patient', 'creation_idempotency_key'), name='singing_session_creation_idempotency_unique'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_creation_idempotency_downgrade),
    ]
