# Generated by Django 5.2.17 on 2026-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('singing', '0004_remove_analysistimeseries_generation'),
        ('songs', '0004_songavailabilityscanstate_batch_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingsession',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='singingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_idempotency_key', ''), _negated=True), fields=('patient', 'creation_idempotency_key'), name='singing_session_creation_idempotency_unique'),
        ),
    ]
