# Generated by Django 5.2.17 on 2026-09-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('singing', '0005_singingsession_creation_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singingsession',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='singing_sessions', to='patients.treatmentplan'),
        ),
        migrations.AlterField(
            model_name='singingsession',
            name='treatment_plan_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
