# Generated by Django 5.2.17 on 2026-10-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_irreversible_schema_barrier'),
        ('singing', '0006_alter_singingsession_treatment_plan_and_more'),
        ('songs', '0007_reference_pitch_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingsession',
            name='playback_accompaniment_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backing_playback_sessions', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='playback_accompaniment_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='playback_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='playback_source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_playback_sessions', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='playback_source_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='reference_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='songs.songreferencepitch'),
        ),
        migrations.AddField(
            model_name='singingsession',
            name='submission_body_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
