# Generated by Django 5.2.17 on 2026-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0008_song_playback_alignment"),
        ('singing', '0007_session_playback'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingsession',
            name='playback_alignment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
