# Generated by Django 5.2 for VocaEase Task 7.
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("normalized_filters", models.JSONField(default=dict)),
                ("selected_ids", models.JSONField(default=list)),
                ("rows_snapshot", models.JSONField(default=list)),
                ("snapshot_count", models.PositiveIntegerField(default=0)),
                ("format", models.CharField(choices=[("csv", "CSV"), ("xlsx", "Excel")], max_length=8)),
                ("status", models.CharField(choices=[("pending", "等待生成"), ("processing", "生成中"), ("ready", "可下载"), ("failed", "生成失败"), ("expired", "已过期")], default="pending", max_length=16)),
                ("failure_reason", models.CharField(blank=True, max_length=256)),
                ("expires_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("creator", models.ForeignKey(on_delete=models.PROTECT, related_name="export_jobs", to=settings.AUTH_USER_MODEL)),
                ("result_asset_id", models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("creator", "idempotency_key"), name="analytics_export_creator_key_unique"),
                    models.CheckConstraint(condition=models.Q(("format__in", ["csv", "xlsx"])), name="analytics_export_format_valid"),
                    models.CheckConstraint(condition=models.Q(("status__in", ["pending", "processing", "ready", "failed", "expired"])), name="analytics_export_status_valid"),
                    models.CheckConstraint(condition=models.Q(("attempt__lte", 4)), name="analytics_export_attempt_limit"),
                    models.CheckConstraint(condition=models.Q(models.Q(("claim_token__isnull", False), ("heartbeat_at__isnull", False), ("lease_expires_at__isnull", False), ("status", "processing")), models.Q(models.Q(("status", "processing"), _negated=True), ("claim_token__isnull", True), ("heartbeat_at__isnull", True), ("lease_expires_at__isnull", True)), _connector="OR"), name="analytics_export_claim_valid"),
                    models.CheckConstraint(condition=models.Q(models.Q(("completed_at__isnull", False), ("result_asset_id__isnull", False), ("status", "ready")), models.Q(("status", "ready"), _negated=True), _connector="OR"), name="analytics_export_ready_result_valid"),
                ],
            },
        ),
    ]
