# Generated by Django 5.2.17 on 2026-08-14 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def retire_legacy_json_snapshot_jobs(apps, schema_editor):
    ExportJob = apps.get_model("analytics", "ExportJob")
    # 旧 pending/processing Job 的唯一患者集合位于即将移除的大 JSON 中，不能
    # 无声生成空文件；转为可恢复失败清理。既有 failed/expired 同样进入统一清理。
    ExportJob.objects.filter(status__in=["pending", "processing"]).update(
        status="failed",
        failure_reason="旧版导出快照已失效，请重新创建导出",
        cleanup_status="pending",
        claim_token=None,
        lease_expires_at=None,
        heartbeat_at=None,
        completed_at=None,
    )
    ExportJob.objects.filter(status__in=["failed", "expired"]).update(
        cleanup_status="pending",
        completed_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJobItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='exportjob',
            name='analytics_export_ready_result_valid',
        ),
        migrations.RemoveField(
            model_name='exportjob',
            name='rows_snapshot',
        ),
        migrations.AddField(
            model_name='exportjob',
            name='cleanup_attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='cleanup_claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='cleanup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='cleanup_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='cleanup_status',
            field=models.CharField(choices=[('none', '无需清理'), ('pending', '等待清理'), ('processing', '清理中'), ('complete', '清理完成')], default='none', max_length=16),
        ),
        migrations.RunPython(retire_legacy_json_snapshot_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cleanup_status', 'none'), ('completed_at__isnull', False), ('result_asset_id__isnull', False), ('status', 'ready')), models.Q(models.Q(('status', 'ready'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='analytics_export_ready_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cleanup_status', 'none'), ('status__in', ['pending', 'processing', 'ready'])), models.Q(('cleanup_status__in', ['pending', 'processing', 'complete']), ('status__in', ['failed', 'expired'])), _connector='OR'), name='analytics_export_cleanup_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cleanup_claim_token__isnull', False), ('cleanup_lease_expires_at__isnull', False), ('cleanup_status', 'processing')), models.Q(models.Q(('cleanup_status', 'processing'), _negated=True), ('cleanup_claim_token__isnull', True), ('cleanup_lease_expires_at__isnull', True)), _connector='OR'), name='analytics_export_cleanup_claim_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cleanup_completed_at__isnull', False), ('cleanup_status', 'complete'), ('result_asset_id__isnull', True)), models.Q(models.Q(('cleanup_status', 'complete'), _negated=True), ('cleanup_completed_at__isnull', True)), _connector='OR'), name='analytics_export_cleanup_complete_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(('result_asset_id__isnull', True), models.Q(('cleanup_status', 'none'), ('status', 'ready')), models.Q(('cleanup_status__in', ['pending', 'processing']), ('status__in', ['failed', 'expired'])), _connector='OR'), name='analytics_export_result_attachment_valid'),
        ),
        migrations.AddField(
            model_name='exportjobitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analytics.exportjob'),
        ),
        migrations.AddConstraint(
            model_name='exportjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'patient_id'), name='analytics_export_item_patient_unique'),
        ),
        migrations.AddConstraint(
            model_name='exportjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'position'), name='analytics_export_item_position_unique'),
        ),
    ]
