# Generated by Django 5.2.17 on 2026-08-14 05:01

from django.db import migrations, models


def invalidate_legacy_availability_snapshots(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    Song.objects.update(
        source_available=False,
        source_verified_at=None,
        source_verified_asset_id=None,
        source_receipt_fingerprint='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_source_availability_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAvailabilityScanState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cursor', models.UUIDField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='song_availability_scan_singleton')],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_backend',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_etag',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_generation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_mime',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_object_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='source_verified_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(invalidate_legacy_availability_snapshots, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='song',
            name='song_source_availability_valid',
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_asset__isnull', False), ('source_available', True), ('source_receipt_fingerprint__gt', ''), ('source_verified_asset_id', models.F('source_asset_id')), ('source_verified_asset_id__isnull', False), ('source_verified_at__isnull', False), ('source_verified_mime__gt', ''), ('source_verified_object_key__gt', ''), ('source_verified_size__isnull', False), models.Q(models.Q(('source_verified_backend', 'local'), ('source_verified_etag', ''), ('source_verified_generation__regex', '^[0-9a-f]{32}$'), ('source_verified_sha256__regex', '^[0-9a-f]{64}$')), models.Q(('source_verified_backend', 'qiniu'), ('source_verified_etag__gt', ''), ('source_verified_generation', ''), ('source_verified_sha256', '')), _connector='OR')), models.Q(('source_available', False), ('source_receipt_fingerprint', ''), ('source_verified_asset_id__isnull', True), ('source_verified_backend', ''), ('source_verified_etag', ''), ('source_verified_generation', ''), ('source_verified_mime', ''), ('source_verified_object_key', ''), ('source_verified_sha256', ''), ('source_verified_size__isnull', True)), _connector='OR'), name='song_source_availability_valid'),
        ),
    ]
