# Generated by Django 5.2.17 on 2026-08-14 05:32

from django.db import migrations, models


def release_legacy_scan_claims(apps, schema_editor):
    ScanState = apps.get_model('songs', 'SongAvailabilityScanState')
    ScanState.objects.update(claim_token=None, lease_expires_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songavailabilityscanstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songavailabilityscanstate',
            name='batch_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songavailabilityscanstate',
            name='pending_batch_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(release_legacy_scan_claims, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='songavailabilityscanstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_token__isnull', True), ('lease_expires_at__isnull', True), ('pending_batch_token__isnull', True)), models.Q(('claim_token__isnull', False), ('lease_expires_at__isnull', False), ('pending_batch_token__isnull', False)), _connector='OR'), name='song_availability_scan_claim_valid'),
        ),
    ]
