# Generated by Django 5.2.17 on 2026-09-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_irreversible_schema_barrier'),
        ('songs', '0004_songavailabilityscanstate_batch_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='accompaniment_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accompaniment_songs', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='song',
            name='ingestion_mode',
            field=models.CharField(choices=[('existing', '现有上传'), ('manual', '人工上传')], default='existing', max_length=16),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lyrics_songs', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='song',
            name='vocal_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vocal_songs', to='media.mediaasset'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('ingestion_mode__in', ['existing', 'manual'])), name='song_ingestion_mode_valid'),
        ),
    ]
