# Generated by Django 5.2.17 on 2026-10-06 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_irreversible_schema_barrier'),
        ('songs', '0005_song_accompaniment_asset_song_ingestion_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongReferencePitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed'), ('stale', 'stale')], default='pending', max_length=16)),
                ('input_fingerprint', models.CharField(blank=True, max_length=64)),
                ('document', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.mediaasset')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_versions', to='songs.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
