# Generated by Django 5.2.17 on 2026-10-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_reference_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='songreferencepitch',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songreferencepitch',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='songreferencepitch',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songreferencepitch',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songreferencepitch',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
